# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imggram', '0002_auto_20170918_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
